"""Build premium template zip for Gumroad distribution.

Includes the template source files (README, source, tests, configs) but
excludes node_modules, dist, and lockfiles that should be generated by users.
"""
import os
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
TEMPLATE_DIR = ROOT / "packages" / "create-mcp-server" / "templates" / "database"
OUTPUT_ZIP = ROOT / "dist" / "premium" / "mcp-server-database-template.zip"

EXCLUDE_DIRS = {"node_modules", "dist", ".git", "__pycache__"}
EXCLUDE_FILES = {"package-lock.json", ".DS_Store"}


def build_zip() -> int:
    if not TEMPLATE_DIR.exists():
        print(f"ERROR: template not found: {TEMPLATE_DIR}")
        return 1

    OUTPUT_ZIP.parent.mkdir(parents=True, exist_ok=True)

    files_added = []
    with zipfile.ZipFile(OUTPUT_ZIP, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, filenames in os.walk(TEMPLATE_DIR):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for f in filenames:
                if f in EXCLUDE_FILES:
                    continue
                full_path = Path(root) / f
                arcname = full_path.relative_to(TEMPLATE_DIR).as_posix()
                zf.write(full_path, arcname)
                files_added.append(arcname)

    print(f"Created: {OUTPUT_ZIP}")
    print(f"Files: {len(files_added)}")
    for a in sorted(files_added):
        print(f"  + {a}")
    return 0


if __name__ == "__main__":
    sys.exit(build_zip())
