"""Build premium template zip for Gumroad distribution.

Usage:
    python build-premium-zip.py [template_name]

    template_name: Name of the template under packages/create-mcp-server/templates/
                   Defaults to "database" if not specified.

Examples:
    python build-premium-zip.py database
    python build-premium-zip.py auth

Includes the template source files (README, source, tests, configs) but
excludes node_modules, dist, and lockfiles that should be generated by users.
"""
import os
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
TEMPLATES_BASE = ROOT / "packages" / "create-mcp-server" / "templates"
OUTPUT_BASE = ROOT / "dist" / "premium"

EXCLUDE_DIRS = {"node_modules", "dist", ".git", "__pycache__"}
EXCLUDE_FILES = {"package-lock.json", ".DS_Store"}


def build_zip(template_name: str) -> int:
    template_dir = TEMPLATES_BASE / template_name
    output_zip = OUTPUT_BASE / f"mcp-server-{template_name}-template.zip"

    if not template_dir.exists():
        print(f"ERROR: template not found: {template_dir}")
        return 1

    output_zip.parent.mkdir(parents=True, exist_ok=True)

    files_added = []
    with zipfile.ZipFile(output_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, filenames in os.walk(template_dir):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for f in filenames:
                if f in EXCLUDE_FILES:
                    continue
                full_path = Path(root) / f
                arcname = full_path.relative_to(template_dir).as_posix()
                # CLI renames _gitignore → .gitignore, but Gumroad zip
                # bypasses the CLI so we must rename here.
                if arcname.endswith("_gitignore"):
                    arcname = arcname.replace("_gitignore", ".gitignore")
                zf.write(full_path, arcname)
                files_added.append(arcname)

    print(f"Created: {output_zip}")
    print(f"Files: {len(files_added)}")
    for a in sorted(files_added):
        print(f"  + {a}")
    return 0


if __name__ == "__main__":
    name = sys.argv[1] if len(sys.argv) > 1 else "database"
    sys.exit(build_zip(name))
